# Generated by Django 4.0.4 on 2022-04-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('start', models.CharField(max_length=200, verbose_name='Point de départ')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('start_alt', models.IntegerField(verbose_name='Altitude de départ (m)')),
                ('alt_min', models.IntegerField(verbose_name='Altitude minimale (m)')),
                ('alt_max', models.IntegerField(verbose_name='Altitude maximale (m)')),
                ('deniv_pos_cumul', models.IntegerField(verbose_name='Dénivelé positif cumulé (m)')),
                ('deniv_neg_cumul', models.IntegerField(verbose_name='Dénivelé négatif cumulé (m)')),
                ('duration', models.IntegerField(verbose_name='Durée (h)')),
                ('difficulty', models.IntegerField(verbose_name='Difficulté (1-5)')),
            ],
        ),
    ]
