# Generated by Django 4.0.4 on 2022-04-19 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(verbose_name='Date de la sortie')),
                ('real_duration', models.IntegerField(verbose_name='Durée réelle (h)')),
                ('nb_people', models.IntegerField(verbose_name='Nombre de participants')),
                ('exp_grp', models.CharField(choices=[('tous_débutants', 'tous débutants'), ('tous_expérimentés', 'tous expérimentés'), ('mixte', 'mixte')], max_length=20)),
                ('weather', models.CharField(choices=[('bonne', 'bonne'), ('moyenne', 'moyenne'), ('mauvaise', 'mauvaise')], max_length=10)),
                ('difficulty_felt', models.IntegerField(verbose_name='Difficulté (1-5)')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
            ],
        ),
    ]
