# Generated by Django 4.0.4 on 2022-04-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_sortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortie',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Difficulté (1-5)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='difficulty_felt',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Difficulté (1-5)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='itineraires.itineraire'),
        ),
    ]
