# Generated by Django 4.0.4 on 2022-04-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0003_rename_user_sortie_user_alter_itineraire_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire'),
        ),
    ]
