# Generated by Django 4.0.4 on 2022-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0004_alter_sortie_itineraire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='exp_grp',
            field=models.CharField(choices=[('tous_débutants', 'Tous débutants'), ('tous_expérimentés', 'Tous expérimentés'), ('mixte', 'Mixte')], max_length=20, verbose_name='Type de randonneur'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='weather',
            field=models.CharField(choices=[('bonne', 'Bonne'), ('moyenne', 'Moyenne'), ('mauvaise', 'Mauvaise')], max_length=10, verbose_name='Météo'),
        ),
    ]
